version: 2.1

orbs:
  node: circleci/node@4.7.0
  sls: circleci/serverless-framework@1.0.1


commands:
  serverless_deploy:
    description: '(Mock) Deploy'
    parameters:
      stage:
        type: string
        default: 'development'
    steps:
      - checkout
      - sls/setup
      - run:
          name: checking Serverless tool
          command: |
            command -v sls
            command -v serverless
      - run:
          name: print Serverles project config
          command: |
            cd src/services/core
            SLS_DEBUG=* sls print --stage << parameters.stage >>
      - run:
          # Interestingly, setting "max-old-space-size" via NODE_OPTIONS env var causes `sls` to exit 4,
          # even for `sls print` command, before we even discuss about deployment.
          environment:
            # max-old-space-size: 2GB
            # trace-exit: allows us to print the Node/V8 error stacktrace
            NODE_OPTIONS: '--max-old-space-size=2048 --trace-exit'
          name: print Serverles project config again, with NODE_OPTIONS env var
          command: |
            cd src/services/core
            SLS_DEBUG=* sls print --stage << parameters.stage >>

jobs:
  deploy_development:
    executor: sls/default
    steps:
      - serverless_deploy:
          stage: 'development'

workflows:
  main:
    jobs:
      - deploy_development
